### ISSUE TITLE
Expand official license warning to support ChannelProviders

### ISSUE THREAD

**Issue by pupnewfster** [neoforged/NeoGradle#1]
As discussed some in this NeoForge PR: https://github.com/neoforged/NeoForge/pull/18#discussion_r1265527811 NeoGradle's `MojangLicenseHelper` currently does not support warning developers about official mappings when they are using a `ChannelProvider` that builds on top of the official mappings.

**Comment by marchermans** [comment]
NG Next has this implemented.
Hopefully that can go live in the next few days.

**Comment by marchermans** [comment]
Has been implemented
