### ISSUE TITLE
[Feature Request] Add DevLogin support to client run configs

### ISSUE THREAD

**Issue by ApexModder** [neoforged/NeoGradle#100]
[DevLogin](https://github.com/covers1624/DevLogin#devlogin) allows users to authenticate their clients using Mojangs services at startup.

Adding DevLogin to any NeoForge mod involves the [following steps currently](https://github.com/covers1624/DevLogin/wiki/NeoGradle).

While this is a simple setup, I think it would make sense for NeoGradle, and potentially other loaders too, to include DevLogin as a feature for their client run configs.
Of course this would have to be a opt-in feature, having it enabled by default wouldn't make much sense IMO.

I am thinking of adding a super simple boolean flag (`authed true`) to client configs, which when enabled
- sets the main class to `net.covers1624.devlogin.DevLogin`
- sets the program arg `--launch_target` to `cpw.mods.bootstraplauncher.BootstrapLauncher`
- and tells DevLogin to use the `default` auth profile via `--launch_profile default`
	There should also be an optional property users can specify to set the profile that DevLogin will use. This will allow users to authenticate their clients with multiple accounts.
	Maybe something like `authProfile <profile>` (if set also sets `authed true`)

**Comment by Gaming32** [comment]
I prefer [DevAuth](https://github.com/DJtheRedstoner/DevAuth) personally. It doesn't require fiddling with the main class. Alternatively, NeoGradle could handle login itself; it's not that hard.
