### ISSUE TITLE
Apply Access Transformer to Mod Dependencies

### ISSUE THREAD

**Issue by vfyjxf** [neoforged/NeoGradle#109]
For years, Access Transformer has allowed runtime privilege escalation for any Class, but it only works for Minecraft at compile time.
Allowing Access Transformer for mods is a great option to help mod authors have direct access to private classes (which is usually encountered during using mixin)

**Comment by shartte** [comment]
I am personally opposed to this. Introducing the need to pre-process any and all mod dependencies (how do you even define what a mod dependency is?) has very large complexity cost.

**Comment by vfyjxf** [comment]
> how do you even define what a mod dependency is?

~~This should be easy enough to simply assume that the dependency marked with `fg.deobf` is a mod,~~(Sorry, I forgot that fg.deobf is no longer needed.)  or a new configuration can be provided to mark the mod that needs to be transformed.(I've tried [this ](https://github.com/vfyjxf/JEI-Utilities/blob/1026a9af96908f8cb7373c3ae0f7ce4ff2872af2/build.gradle#L174-L231)in a project and it works, but it doesn't have a caching system and causes a occasionally file locking.)

**Comment by pupnewfster** [comment]
I am also opposed to this, as back in the FG2 days of 1.12.2 ATs were applied at compile time from deps and it led to a good number of bugs so was changed for FG3. For example from mods depending on an optional dependency's AT and not knowing that at runtime the method or field would not be accessible. The general consensus is if you need ATs that your deps also use just copy them into your own AT file.

**Comment by TelepathicGrunt** [comment]
I feel like I gotten the issue on Arch where a dep AW something to public in common source and I relied on it by mistake and exploded on forge… multiple times… 

Heck no. Please do not allow dep’s ATs to apply to source. I rather not have hell trying to figure out what is actually public vs AT’ed in my source because I do a ton of optional mod compatibility so I end up having a ton of mod dep in my workspaces (unless I am misreading what you’re asking for)

If it is just about applying ATs onto deps, that’s also not a good idea due to time increase on project load. And you already said you’re doing a mixin so just make an accessor mixin for your work anyway

**Comment by Technici4n** [comment]
No, this is something else. This is about transforming classes **defined inside other mods**. That will never be a feature worth supporting from a toolchain perspective in my opinion. Mods are normal jar dependencies in NeoGradle 7+ and that's not going to change.

**Comment by lukebemish** [comment]
> > how do you even define what a mod dependency is?
> 
> ~This should be easy enough to simply assume that the dependency marked with `fg.deobf` is a mod,~(Sorry, I forgot that fg.deobf is no longer needed.) or a new configuration can be provided to mark the mod that needs to be transformed.(I've tried [this ](https://github.com/vfyjxf/JEI-Utilities/blob/1026a9af96908f8cb7373c3ae0f7ce4ff2872af2/build.gradle#L174-L231)in a project and it works, but it doesn't have a caching system and causes a occasionally file locking.)

Just to note - that sort of post processing of dependencies in `afterEvaluate` is a bad idea for a number of different reasons. It's basically what `fg.deobf` did, more or less, and it pretty much makes any sort of compatability with stuff like included builds basically impossible. You're also transforming the jars on the disk - messing stuff up for dependencies stored between projects. Making something like this work in NG itself, in a way that doesn't mess stuff up in any number of different cases, is basically impossible without bringing back the sort of cursed processing of dependency jars that NG7 got rid of.
