### ISSUE TITLE
Parchment not being applied to neogradle-vanilla

### ISSUE THREAD

**Issue by ApexModder** [neoforged/NeoGradle#120]
I have setup a multi-project workspace using NeoGradle for both a `vanilla` project and `neoforge` project.

When applying parchment it applies correctly to the NeoForge project but not the Vanilla project.

<details>

<summary>Screenshots</summary>

### NeoForge - Left | Vanilla - Right

![image](https://github.com/neoforged/NeoGradle/assets/29412632/b6eb6476-7867-4a04-bf72-809df1fe0bad)

</details>

[Example repo](https://github.com/ApexModder/NeoGradle-Vanilla-Parchment-Issue)

**Comment by Gaming32** [comment]
For me it's the opposite. It only applies to the Vanilla subproject.

**Comment by ApexModder** [comment]
After some investigations turns out I was just using an outdated version of NeoGradle which only supported Parchment on `userdev`.

Updating to NeoGradle `7.0.88` (or newer) fixes this issue for me.
