### ISSUE TITLE
Invalid client extra jar in NeoDev

### ISSUE THREAD

**Issue by pupnewfster** [neoforged/NeoGradle#121]
Using NG 7.0.93, for some reason neodev with NG 7.0.94 gives [this error output](https://gist.github.com/pupnewfster/2c0f7ca51ca820042b18842898999210) when I try to do `runData`  but if I downgrade to 7.0.93 it works fine. 

likely not super relevant [discord mention](https://discord.com/channels/313125603924639766/801175194298744902/1210704816641155142)

**Comment by marchermans** [comment]
Should be fixed now.
