### ISSUE TITLE
File locking for unknown reasons, when using multiple mod sourceSets.

### ISSUE THREAD

**Issue by vfyjxf** [neoforged/NeoGradle#125]
see the title.
the [logs ](https://gist.github.com/vfyjxf/ca69349dd00b09b335f867cb916da21e)with stacktrace.
[project ](https://github.com/vfyjxf/Cyclone)repo

**Comment by marchermans** [comment]
Can you try updating to the latest neogradle and check again?

**Comment by vfyjxf** [comment]
I think it's been fixed, the latest neogradle works great!
