### ISSUE TITLE
Add handling for pom dependencies

### ISSUE THREAD

**Issue by AterAnimAvis** [neoforged/NeoGradle#144]
When adding a dependency on something like <https://mvnrepository.com/artifact/org.graalvm.polyglot/python/23.1.2>, Gradle will resolve this to the `pom` and pull in it's dependencies transitively.

Resolving the dependency directly will result in the `.pom` file, `UnionFileSystem` expects entries to be a zip/jar/directory, adding the pom resulting in `ProviderNotFoundException`s in `UnionFileSystem#openFileSystem` at runtime.

[Originally from Discord](https://discord.com/channels/313125603924639766/801175194298744902/1229727626869084241)

**Comment by marchermans** [comment]
Can I get an example for this, so that I can write a unit test and debug it?
