### ISSUE TITLE
Per-project caches use large amounts of disk space

### ISSUE THREAD

**Issue by lukebemish** [neoforged/NeoGradle#15]
With old FG, forge and minecraft were cached universally in `~/.gradle/caches`. With NG 7, neoforge and MC both are each downloaded and cached _per project_ - that is, the `client.jar`, `server.jar`, client extra, neoforged, and neoforged sources are stored in the project-level `.gradle` cache of every project that uses neogradle. This is a really good way to eat up a ton of disk space, which FG was already bad enough at.

**Comment by lukebemish** [comment]
Actually, it's worse than that - there's stuff in `build/neoForm` that looks pretty big too

**Comment by LlamaLad7** [comment]
Running `clean` also wipes the cache...

**Comment by lukebemish** [comment]
This issue should not be closed. NeoGradle still uses ~450 MiB of disk space per project, which is a definite improvement over the ~1 GiB it used to but is still an absolute ton.
