### ISSUE TITLE
Feature Request: Function to make a dependency get used only during building or runData

### ISSUE THREAD

**Issue by Zepalesque** [neoforged/NeoGradle#166]
I’m *hoping* this is the correct place to open this, if not then it’d be nice if I could be redirected to the correct place

Anyway, my feature request is essentially a way, similar to things like `implementation`, `runtimeOnly`, or `compileOnly`, a way to specify that a dependency should only be used either while building the mod or when running datagen (and in the IDE, idk if that’s seperate though)

This would be useful for when you might want to implement cross-mod compat that references other mods inside the datagen, but don’t necessarily want to have the mod in the `runClient` task (or `runServer` either I suppose)

Maybe something like `dataCompile` would work? I would try to implement it myself and make a pull request, but I have _no_ clue how gradle’s inner workings work lol

**Comment by marchermans** [comment]
You can just add dependencies to each run, with the runs dependency handler.
Would that work? Check out: https://github.com/neoforged/NeoGradle?tab=readme-ov-file#including-the-sibling-project-in-your-run or https://github.com/neoforged/NeoGradle?tab=readme-ov-file#run-specific-dependency-management

**Comment by Zepalesque** [comment]
oh yeah, that seems perfect! thanks!
