### ISSUE TITLE
NeoGradle 7.0.126 crashes at boot

### ISSUE THREAD

**Issue by thedarkcolour** [neoforged/NeoGradle#169]
The latest version of NeoGradle fails to load the game. However, leaving the version as 7.0.124 works just fine.

### Steps to reproduce:
1. Clone the [neoforged/MDK](https://github.com/neoforged/MDK/tree/dad00053f00af616e8e26171383427f52988fd1f)
2. Change the NeoGradle version in `build.gradle` to `7.0.126`
3. Run Client
4. Crashes before early loading screen appears

[debug log](https://gist.github.com/thedarkcolour/e32dc68fabd161748aee0e4078d074e7)

**Comment by AugustoMegener** [comment]
The same happened to me, every time the entire Client runs, a crash occurs.

[log.txt](https://github.com/neoforged/NeoGradle/files/15326404/log.txt)

**Comment by marchermans** [comment]
Fixed in the latest release.
