### ISSUE TITLE
Duplicate JAR file as a result of NeoGradle?

### ISSUE THREAD

**Issue by Kitteh6660** [neoforged/NeoGradle#182]
Now I don't know what is up with it, but for some reason, when I import NeoForge or refresh Gradle project, there is a tendency for duplicate NeoForge JAR file.

I was using Eclipse if that helps.

![image](https://github.com/neoforged/NeoGradle/assets/5838739/e2d7efa4-5d07-4021-9d98-688f3cad2797)

If needed, I can provide build.gradle files.

**Comment by Shadows-of-Fire** [comment]
I've seen this a couple times, typically after manually removing the second jar it never shows back up, though I don't know why it happens in the first place.

**Comment by marchermans** [comment]
Interesting, yeah the jar exists in two configurations, but it is to the object down even the same dependency, with the same resolution path.

Not sure why eclipse would import it twice

I don't have much hope however in tracking this, since I have not enough experience with eclipse.

**Comment by lukebemish** [comment]
Just to clarify, what adverse effects does the duplicate jar have in eclipse? Always good to know what issues this actually leads to.

**Comment by Kitteh6660** [comment]
It causes build errors, and Eclipse to complain. It may break building.

It sometimes happen when importing NeoForge projects.
