### ISSUE TITLE
[NG7] Minecraft setup multiple times when including multiple NG projects

### ISSUE THREAD

**Issue by ApexModder** [neoforged/NeoGradle#186]
Gradle setups Minecraft for each included NG project, making imports slow and workspaces tedious to use as there are duplicate Minecraft source entries.

Would be nice if we could mark a single project to be used for all Minecraft source related tasks, and have all NG projects use the Minecraft sources from that project.

[_original discussion in NeoCord_](https://discord.com/channels/313125603924639766/1239579489617580072/1243611864567382159)

**Comment by thedarkcolour** [comment]
I can also vouch for this. The workspace I use for Kotlin for Forge takes 10+ minutes to import on my laptop, and anytime I accidentally mess up the cache I have to wait another 10 minutes for Neo to do the same work three times. I know factors like AccessTransformers, Parchment mappings, and NeoGradle version could mess things up but when they're all the same I think it would make sense to reuse the dependencies across projects like ForgeGradle used to.

Not to mention the multiple Minecraft sources are a big resource hog.

**Comment by tmvkrpxl0** [comment]
I heard Orion was working on better caching system, maybe it's relevant?

**Comment by thedarkcolour** [comment]
This is still not working properly...

**Comment by thedarkcolour** [comment]
https://github.com/thedarkcolour/KotlinForForge/tree/4.x
