### ISSUE TITLE
Move ToolActions to tags (1.21+?)

### ISSUE THREAD

**Issue by Tslat** [neoforged/NeoGradle#189]
I'm not entirely sure I see the reason here for keeping the ToolActions system in NeoForge given Mojang's move to data driven content, and the fact that it basically does the same thing as tags

Can we investigate the feasibility of moving this system to tags so we can make it natively data-driven and eliminate any technical debt involved

**Comment by TelepathicGrunt** [comment]
Isn't the purpose of toolactions for supporting nbt based itemstacks? Or as of 1.21+, component based itemstacks. @knightminer would be good to ask about it. If anything, I would expect components to replace toolactions, not tags.

**Comment by Shadows-of-Fire** [comment]
Yes, it is.  Tags are not a suitable replacement.  Also, why is this on the NG repo

**Comment by Tslat** [comment]
I only just noticed I'm in Neogradle repo not NeoForge -.-
