### ISSUE TITLE
Unable to use NeoForge/NeoGradle in Multi Project setups. 

### ISSUE THREAD

**Issue by mysticdrew** [neoforged/NeoGradle#19]
Currently using 
https://github.com/jaredlll08/MultiLoader-Template
For most of my mods. 

When setting up a NeoForge setup it fails with 
```
An exception occurred applying plugin request [id: 'net.neoforged.gradle.userdev', version: '[7.0.5,)']
> Failed to apply plugin class 'net.neoforged.gradle.common.CommonProjectPlugin'.
   > Could not create an instance of type net.neoforged.gradle.common.extensions.IdeManagementExtension.
      > Failed to apply plugin class 'org.jetbrains.gradle.ext.IdeaExtPlugin'.
         > Cannot add extension with name 'settings', as there is an extension already registered with that name.
```

Other devs have said they have experienced similar issues. 

Current project
https://github.com/mysticdrew/common-networking/tree/1.20.2-add-neoforged
commit: https://github.com/mysticdrew/common-networking/commit/cf1120f132271aff6801a51d4beafb1b202881af

**Comment by marchermans** [comment]
Both VanillaGradle and Userdev are applying the idea plugin......

**Comment by NovaMachina** [comment]
I also ran into this issue in a multi-mod project. While the 1.20 version of this has not been pushed, it has the general idea of what I'm working with: https://github.com/NovaMachina-Mods/MultiWorkspace

**Comment by ricksouth** [comment]
I'm also using Multiloader. Would be great to see support added for it.

**Comment by SquidDev** [comment]
A possible workaround might be to use NG's vanilla plugin instead of VanillaGradle - that appears to be working for me at least.

**Comment by Kotori316** [comment]
In my environment, replacing to NeoForge Vanilla plugin didn't solve this problem. I used `net.neoforged.gradle.vanilla` but it also applies `gradle.plugin.org.jetbrains.gradle.plugin.idea-ext:gradle-idea-ext:1.1.6` via `net.neoforged.gradle:common:7.0.8`
Code: https://github.com/Kotori316/AutoPlanter/tree/1.20.2_ng_vanilla
CI: https://github.com/Kotori316/AutoPlanter/actions/runs/6715925545/job/18251428772#step:6:26

**Comment by lukebemish** [comment]
What happens if you apply the idea plugin manually at the root project?

**Comment by Kotori316** [comment]
Adding `id "org.jetbrains.gradle.plugin.idea-ext" version "1.1.7"` in plugins block at the root `build.gradle` solved importing issue(VanillaGradle). The plugin tries to run `idePostSync` task and fails in common module where the task doesn't exist, but this is not a problem for me.

**Comment by mysticdrew** [comment]
So this fix did not fully work for me, 
However, adding this thanks to @Kotori316 did allow me to progress further. 
```
plugins {
    id "org.jetbrains.gradle.plugin.idea-ext" version "1.1.7"
}
```

Some other issues, I have a couple mods I depend on in the `neoforge `and `common `packages. 
However, neoforge cannot find them from `common`
Now, it cannot find any packages from dependencies located in the common package.
I'll see if I can get a test mod to show this.

Another issue
Running Indev there are module issues

Feel free to clone and run indev to see the module error
https://github.com/mysticdrew/common-networking

`Module minecraft contains package commonnetwork, module commonnetworking exports package commonnetwork to minecraft`

**Comment by mysticdrew** [comment]
@marchermans I'd reopen this, since the issues are still not resolved but I am unable to reopen. 
Thanks.

**Comment by marchermans** [comment]
> .

If you encounterot then please post a log. It might be that VanillaGradle needs to also make fixes

**Comment by mysticdrew** [comment]
> If you encounterot then please post a log. It might be that VanillaGradle needs to also make fixes

The error is the exact same as the initial one I posted when I created the issue. 
Full log: 
https://gist.github.com/mysticdrew/78cecb7e920f213adbaea5ca14c491dc

adding this line in the root build.gradle stops that error from happening, then neogradle cannot locate dependencies from the common module it seems.

```
plugins {
    id "org.jetbrains.gradle.plugin.idea-ext" version "1.1.7"
}
```

However, when the project does not have any dependencies in common, the project will build and run in production just fine. But it is un-runnable indev due to module errors listed above.

**Comment by Tslat** [comment]
Reopen this please.

I still cannot run a multiloader setup with NeoForge without requiring that additional plugin definition from the post above.
This is not fixed.

**Comment by PssbleTrngle** [comment]
I'm also still encountering the same issue, with the latest version of neogradle & neogradle common plugin.
Even when specifying the `org.jetbrains.gradle.plugin.idea-ext` plugin in the root file, I still get the error
```
Cannot add extension with name 'unitTests', as there is an extension already registered with that name
```

Did somebody find a workaround on how to use these plugins in a multi-project setup?

**Comment by lukebemish** [comment]
Make _all_ of your plugins `apply: false` in your root build script, and apply them in subprojects by ID only, and this will not occur. This is good practice anyways to avoid any number of other classpath related issues. See https://docs.gradle.org/current/userguide/plugins_intermediate.html#sec:root_plugins_dsl

**Comment by PssbleTrngle** [comment]
@lukebemish I do not apply any of the neoforge plugins in my root project, just some that I actually want there, like sonarqube or spotless

**Comment by lukebemish** [comment]
Yes. _Declare_ all plugins in your root project with `apply: false`, then apply the relevant ones in subprojects by ID. If you want to be extra fancy declare them all in your settings.gradle file. Either way you avoid a lot of potential classpath issues especially if you have lots of plugins involved.

**Comment by PssbleTrngle** [comment]
Is see, this does not work out for my current setup, as there are a few plugins I actually want to have applied in the root project, but thank you for your help anyway. 
I still don't fully understand how this causes a classpath issue in my case, since the neoforge plugins are only loaded and applied within the subprojects and no plugin that is applied in the root project loads the idea-ext plugin

**Comment by lukebemish** [comment]
Well then you apply _those_ plugins without `apply: false` in your root project. This is a standard way of applying plugins that avoids any issue like the one this issue originally related to by avoiding classpath wackiness with plugins that configure across projects or use build services.

**Comment by lukebemish** [comment]
If doing what I suggested -- which is a good idea in general to avoid issues, and definitely solves this issue -- does _not_ solve the issue, then you're looking at a different issue and you should probably open a new issue with more details than the single line error -- importantly, a full log and how to reproduce it.
