### ISSUE TITLE
`Current thread does not hold the state lock for project X` on multi project setup

### ISSUE THREAD

**Issue by andriihorpenko** [neoforged/NeoGradle#195]
## Description
I have a multi project setup with `org.gradle.parallel` set to `true`. I am getting `Current thread does not hold the state lock for project X` exception while syncing the project. Setting the mentioned property above to `false` resolves the issue.

## Stacktrace
https://bytebin.lucko.me/9eDjPqntKg

## Notes
- NeoGradle version: 7.0.138
- See the following [Discord message](https://discord.com/channels/313125603924639766/1185197721477468160/1246785443287142463) for more info.

**Comment by marchermans** [comment]
Fixed in the latest release try 7.0.138
