### ISSUE TITLE
Plugin requires java 17, when gradle can still be run with java 8 (while building for java 17)

### ISSUE THREAD

**Issue by solonovamax** [neoforged/NeoGradle#205]
Currently, the gradle plugin requires java 17: https://github.com/neoforged/NeoGradle/blob/48ae9fa3bf61b5088109a15cd13b0bf526e85784/build.gradle#L62

This is problematic for me, as I'm making a gradle plugin which has an *optional* dependency on neogradle. (it aims to be a plugin to easily configure a bunch of things for my different projects, some of which are mc projects, others which are not) I would like to still be able to target buildscripts that use java 8/11.
Because it is set to require java 17, it cannot target those buildscripts.

Additionally, gradle can still actually be ran using gradle 8, so long as it can locate a java 17 jdk (see: gradle toolchains), and still build targeting java 17 or greater. The jdk used to invoke gradle != the jdk used to build the project.

**Comment by solonovamax** [comment]
Though, this would restrict which jdk apis you have access to and can use in neogradle.

Perhaps, it could be lessened to compile for jdk 11?

**Comment by lukebemish** [comment]
With the new gradle daemon toolchain feature in gradle 8.8, this is basically irrelevant -- if you want to ensure that gradle runs with java 17 or whatever, you just set the daemon toolchain to that.

**Comment by lukebemish** [comment]
If you're trying to depend on it as an optional dependency in some java 8 code, that should still be possible. You'll need to compile the code that touches NG with a newer JVM, targeting an older one.

**Comment by solonovamax** [comment]
> If you're trying to depend on it as an optional dependency in some java 8 code, that should still be possible. You'll need to compile the code that touches NG with a newer JVM, targeting an older one.

no...?

when attempting to set the jvm *target* to `8` (the jvm *toolchain* is set to 21), the following error is produced:
```
Execution failed for task ':compileKotlin'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not resolve net.neoforged.gradle:userdev:7.0.142.
     Required by:
         project : > net.neoforged.gradle.userdev:net.neoforged.gradle.userdev.gradle.plugin:7.0.142
      > No matching variant of net.neoforged.gradle:userdev:7.0.142 was found. The consumer was configured to find a library for use during compile-time, compatible with Java 8, preferably in the form of class files, preferably optimized for standard JVMs, and its dependencies declared externally, as well as attribute 'org.gradle.plugin.api-version' with value '8.8', attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm' but:
          - Variant 'apiElements' declares a library for use during compile-time, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.gradle.plugin.api-version' with value '8.7':
              - Incompatible because this component declares a component, compatible with Java 17 and the consumer needed a component, compatible with Java 8
              - Other compatible attributes:
                  - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)
                  - Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'jvm')
          - Variant 'runtimeElements' declares a library for use during runtime, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.gradle.plugin.api-version' with value '8.7':
              - Incompatible because this component declares a component, compatible with Java 17 and the consumer needed a component, compatible with Java 8
              - Other compatible attributes:
                  - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)
                  - Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'jvm')
          - Variant 'sourcesElements' declares a component for use during runtime, and its dependencies declared externally:
              - Incompatible because this component declares documentation and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about its elements (required them preferably in the form of class files)
                  - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)
                  - Doesn't say anything about its target Java version (required compatibility with Java 8)
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.8')
                  - Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'jvm')

* Try:
> No matching variant errors are explained in more detail at https://docs.gradle.org/8.8/userguide/variant_model.html#sub:variant-no-match.
> Review the variant matching algorithm at https://docs.gradle.org/8.8/userguide/variant_attributes.html#sec:abm_algorithm.
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
```

this is because the published api of neogradle *requires* a jdk >= 17, so it cannot be depended on in a project that targets jdk 8 or jdk 11.

if I change the jvm *target* from 8 to 17, then it compiles.

**Comment by solonovamax** [comment]
Note the most important part:
> Incompatible because this component declares a component, **compatible with Java 17** and *the consumer* needed a component, **compatible with Java 8**

**Comment by lukebemish** [comment]
Yes, I'm aware how variants work. You'll want to compile the code that touches NG with a higher JVM, targeting a lower JVM. And since the requested attribute is derived from the targeted JVM by default, you'll probably want to do that in a separate source set. Regardless, that's something that can fully be solved on your end.

**Comment by solonovamax** [comment]
> Yes, you'll want to compile the code that touches NG with a higher JVM, targeting a lower JVM

that is precisely what I was doing. I compiled with a higher jvm (jdk 21), targetting a lower jvm (jdk 8), but it still did not work, as you indicated.

**Comment by lukebemish** [comment]
This is not exactly an uncommon thing to do. I mean heck, look at how any old build working with a multirelease jar ends up working. You'll want a separate source set for safety (though technically you can do it all in a main source set), request the correct version of the java version attribute, and call it a day.

**Comment by solonovamax** [comment]
> You'll want a separate source set for safety (though technically you can do it all in a main source set), request the correct version of the java version attribute, and call it a day

wdym by, "request the correct version of the java version attribute"?

**Comment by lukebemish** [comment]
This is why I'd use a separate source set. You can just set the jvm version attribute for the classpath of that source set to 17.

**Comment by solonovamax** [comment]
but then I wouldn't be able to depend on that other source set?

**Comment by lukebemish** [comment]
You could do the same with your main source set though it's technically marginally less safe. And you wouldn't depend on the other source set...? You'd just include the compiled classes from it. Or depend on its output at compile I suppose but that doesn't have attributes so it'll be fine.

**Comment by solonovamax** [comment]
Then how would it be included into a single gradle plugin...?

**Comment by lukebemish** [comment]
Depend on its outputs at compile, shadow its outputs when publishing...?

**Comment by solonovamax** [comment]
but I wouldn't be able to add it to the compile classpath as the target jdk of the second source set is greater than the target jdk of the main source set of my plugin, no?

**Comment by lukebemish** [comment]
No clue what you're talking about. That's why you set the jvm version attribute on whatever compile classpath you want to pull NG into to 17. And for adding the other source set to the main one -- it doesn't matter there, because the outputs have no attributes

**Comment by solonovamax** [comment]
but also, I would like to do this inside of a single source set without significant nasty hacks. I don't particularly want to have two source sets.

**Comment by lukebemish** [comment]
you want to have code targeting java 8 as well as stuff targeting java 17...
...but you don't want more than one source set? It's definitely possible, but I'd argue that you're on your own there, because NG targets java 17 and I doubt that's going to change because there's no good reason for it to.

**Comment by solonovamax** [comment]
> you want to have code targeting java 8 as well as stuff targeting java 17...

no, I don't *want* to target java 17. I only want to target java 8, but neo is forcing me to target java 17.

**Comment by Matyrobbrt** [comment]
NG is targeting Java 17 and will continue to do so. As was pointed out in this thread, there are solutions that can avoid locking your own plug-in into Java 17, however I'd recommend just making your plugin run on 17.
