### ISSUE TITLE
neoFormJoined[...]DownloadAssets task error in multiprojects

### ISSUE THREAD

**Issue by mezz** [neoforged/NeoGradle#207]
When I try `./gradlew build` on my project, I get this error:

`Reason: Task ':NeoForgeApi:neoFormJoined1.20.6-20240429.153634DownloadAssets' uses this output of task ':NeoForge:neoFormJoined1.20.6-20240429.153634DownloadAssets' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
`

full log: https://gist.github.com/mezz/b20871b078635a5b100ba49182a4dfd3
my current code is here: https://github.com/mezz/JustEnoughItems/pull/3529 

my understanding is that my `:NeoForgeApi` project is using output from the same-named task in `:NeoForge`, but it is not declared explicitly

this is pretty concerning, because `:NeoForgeApi` does not depend on the `:NeoForge` project at all
let me know if there's any additional info I can provide to help

**Comment by TBoshoven** [comment]
I have the same issue in a multiproject build:
```
> Task :MagicMirror:neoFormJoined1.20.6-20240429.153634DownloadAssets FAILED

FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':MagicMirror:neoFormJoined1.20.6-20240429.153634DownloadAssets' (type 'DownloadAssets').
  - Gradle detected a problem with the following location: '/home/tom/.gradle/caches/minecraft/assets/1.20.6'.
    
    Reason: Task ':MagicMirror:neoFormJoined1.20.6-20240429.153634DownloadAssets' uses this output of task ':MagicDoorknob:neoFormJoined1.20.6-20240429.153634DownloadAssets' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
```

This specifically breaks when I run `./gradlew build` (locally but also in CI with a clean cache).
Other commands like `./gradlew :MagicMirror:runClient` work fine.

**Comment by mezz** [comment]
I am working around this for now by running each project's build separately instead of with `./gradlew build`
See [mezz/JustEnoughItems@`fbb53cb` (#3529)](https://github.com/mezz/JustEnoughItems/pull/3529/commits/fbb53cb441a341a24ae6d3dc53b9c5775a006464)

**Comment by cech12** [comment]
I have the same issue in my multiloader environment and I worked around this by adding following line to my neoforge `build.gradle` file:

```
test.onlyIf { false }
```
