### ISSUE TITLE
Failed to create binary representation for type net.neoforged.fml.common.asm.enumextension.ExtensionInfo

### ISSUE THREAD

**Issue by Spinoscythe** [neoforged/NeoGradle#212]
```
> Task :NeoForge:neoFormApplyParchment
Failed to create binary representation for type net.neoforged.fml.common.asm.enumextension.ExtensionInfo
Failed to create binary representation for type net.neoforged.fml.common.asm.enumextension.ExtensionInfo
Failed to create binary representation for type net.neoforged.fml.common.asm.enumextension.ExtensionInfo
Failed to create binary representation for type net.neoforged.fml.common.asm.enumextension.ExtensionInfo
Failed to create binary representation for type net.neoforged.fml.common.asm.enumextension.ExtensionInfo
Failed to create binary representation for type net.neoforged.fml.common.asm.enumextension.ExtensionInfo
Failed to create binary representation for type net.neoforged.fml.common.asm.enumextension.ExtensionInfo
Failed to create binary representation for type net.neoforged.fml.common.asm.enumextension.ExtensionInfo
Failed to create binary representation for type net.neoforged.fml.common.asm.enumextension.ExtensionInfo
Failed to create binary representation for type net.neoforged.fml.common.asm.enumextension.ExtensionInfo
Failed to create binary representation for type net.neoforged.fml.common.asm.enumextension.ExtensionInfo
Failed to create binary representation for type net.neoforged.fml.common.asm.enumextension.ExtensionInfo
Failed to create binary representation for type net.neoforged.fml.common.asm.enumextension.ExtensionInfo
```

**Comment by marchermans** [comment]
This is now fixed

**Comment by croakcali** [comment]
> Task :neoFormApplyParchment
Failed to create binary representation for type net.neoforged.fml.loading.EarlyLoadingScreenController
Failed to create binary representation for type net.neoforged.fml.common.asm.enumextension.ExtensionInfo
Failed to create binary representation for type net.neoforged.fml.common.asm.enumextension.ExtensionInfo
Failed to create binary representation for type net.neoforged.fml.common.asm.enumextension.ExtensionInfo
Failed to create binary representation for type net.neoforged.fml.common.asm.enumextension.ExtensionInfo
Failed to create binary representation for type net.neoforged.fml.common.asm.enumextension.ExtensionInfo
Failed to create binary representation for type net.neoforged.fml.common.asm.enumextension.ExtensionInfo
Failed to create binary representation for type net.neoforged.fml.common.asm.enumextension.ExtensionInfo
Failed to create binary representation for type net.neoforged.fml.common.asm.enumextension.ExtensionInfo
Failed to create binary representation for type net.neoforged.fml.common.asm.enumextension.ExtensionInfo
Failed to create binary representation for type net.neoforged.fml.common.asm.enumextension.ExtensionInfo
Failed to create binary representation for type net.neoforged.fml.common.asm.enumextension.ExtensionInfo
Failed to create binary representation for type net.neoforged.fml.event.lifecycle.FMLCommonSetupEvent
Failed to create binary representation for type net.neoforged.fml.common.asm.enumextension.ExtensionInfo
Failed to create binary representation for type net.neoforged.fml.common.asm.enumextension.ExtensionInfo

getting the same message after opening custom modgenerator folder in IntelliJ

**Comment by Haru-Kay** [comment]
Bumping this to say it also occurs while running initial environment setup.
`neo_version=21.1.209`
```
IntelliJ IDEA 2022.3.3 (Community Edition)
Build #IC-223.8836.41, built on March 9, 2023
Runtime version: 17.0.6+1-b653.34 amd64

Non-Bundled Plugins:
    org.jetbrains.kotlin (223-1.9.10-release-459-IJ8836.35)
    com.demonwav.minecraft-dev (2022.3-1.6.11)

Kotlin: 223-1.9.10-release-459-IJ8836.35
```

**Comment by Haru-Kay** [comment]
> Bumping this to say it also occurs while running initial environment setup. `neo_version=21.1.209`
> 
> ```
> IntelliJ IDEA 2022.3.3 (Community Edition)
> Build #IC-223.8836.41, built on March 9, 2023
> Runtime version: 17.0.6+1-b653.34 amd64
> 
> Non-Bundled Plugins:
>     org.jetbrains.kotlin (223-1.9.10-release-459-IJ8836.35)
>     com.demonwav.minecraft-dev (2022.3-1.6.11)
> 
> Kotlin: 223-1.9.10-release-459-IJ8836.35
> ```

Updating IntelliJ to the current 2025 version fixed the issue for me
