### ISSUE TITLE
NeoForge 20.2 installer manifest include invalid universal jar

### ISSUE THREAD

**Issue by Scrumplex** [neoforged/NeoGradle#23]
**Minecraft Version:** 1.20.2

**NeoForge Version:** 20.2.20-beta

**Logs:** N/A

**Description of issue:**
Installers for NeoForge 20.2.x use the wrong version number for the universal jar file.

For example `neoforge-20.2.20-beta-installer.jar` includes this file: `maven/net/neoforged/neoforge/1.20.2-20.2.20-beta/neoforge-1.20.2-20.2.20-beta-universal.jar`

Additionally, the install_profile.json includes the following artifact:
```json
{
  "name": "net.neoforged:neoforge:1.20.2-20.2.20-beta:universal",
  "downloads": {
    "artifact": {
      "sha1": "946b6a5096b7bbd9c6a624ee2060641dd2947a6e",
      "size": 2134057,
      "url": "https://maven.neoforged.net/releases/net/neoforged/neoforge/20.2.20-beta/neoforge-20.2.20-beta-universal.jar",
      "path": "net/neoforged/neoforge/1.20.2-20.2.20-beta/neoforge-1.20.2-20.2.20-beta-universal.jar"
    }
  }
}
```

While this is fine for local installation, our tooling for Prism Launcher has to patch this to the right version `20.2.20-beta` so that our clients can download this file from the maven repository.

Confirm yourself using `jq '.libraries[] | select(.name | contains("universal"))' install_profile.json`

**Comment by sciwhiz12** [comment]
Seems to be an issue in NeoGradle itself; NeoGradle assumes in multiple places that the artifact/publishing version is `<mc version>-<project version>`.

Notable higlights: https://github.com/neoforged/NeoGradle/blob/fc21e44f2c4af5a6121ce31c8797a4557741a8b7/platform/src/main/java/net/neoforged/gradle/platform/extensions/DynamicProjectExtension.java#L419 (installer profile JSON), https://github.com/neoforged/NeoGradle/blob/fc21e44f2c4af5a6121ce31c8797a4557741a8b7/platform/src/main/java/net/neoforged/gradle/platform/extensions/DynamicProjectExtension.java#L489 (packed universal JAR, see also neoforged/NeoForge#209).

**Comment by marchermans** [comment]
@Scrumplex The metadata is correct as far as I can see.....
The maven coordinate path of the file has 20.2.X as version number, but the game needs it to be prefixed with the mc version and a dash. Hence that artifact setup.

**Comment by Scrumplex** [comment]
> @Scrumplex The metadata is correct as far as I can see..... The maven coordinate path of the 

Taking as an example: The installer profile specifies `net.neoforged:neoforge:1.20.2-20.2.28-beta:universal`, while the maven only has `net.neoforged:neoforge:20.2.28-beta:universal`. See https://maven.neoforged.net/#/releases/net/neoforged/neoforge/20.2.28-beta

So if anyone is installing NeoForge without the universal jar that's bundled in the installer, it won't work without patching this discrepancy

**Comment by marchermans** [comment]
> > @Scrumplex The metadata is correct as far as I can see..... The maven coordinate path of the
> 
> Taking as an example: The installer profile specifies `net.neoforged:neoforge:1.20.2-20.2.28-beta:universal`, while the maven only has `net.neoforged:neoforge:20.2.28-beta:universal`. See https://maven.neoforged.net/#/releases/net/neoforged/neoforge/20.2.28-beta
> 
> So if anyone is installing NeoForge without the universal jar that's bundled in the installer, it won't work without patching this discrepancy

There is an explicit URL given to you, in the manifest! I don't see the confusion here. There is nothing for you to do, but to download the URL and put it in your libraries path.....

**Comment by Scrumplex** [comment]
Hmm. I kinda managed to overlook that url. Shouldn't the coordinate still match the version used in the maven repository though?

**Comment by marchermans** [comment]
Functionally: no.
Specification wise: no
Is good: no

To fix this requires updating fml, neogradle, and neoforge all at once which is not really trivial. It will happen but not anytime soon I think.

**Comment by Scrumplex** [comment]
After some code changes, I am now making use of the `url` field. So if this is intended behavior, this issue can be closed

**Comment by marchermans** [comment]
> After some code changes, I am now making use of the `url` field. So if this is intended behavior, this issue can be closed

It is not intended perse.
This is at the moment a consequence of our internal versioning scheme in the GAV,and how FML wants its artifacts to be fed to it.
It basically looks for forge, and it needs to have versioning scheme of: `<mcversion>-<forgeversion>` on the file name. While our maven only publishes `<forgeversion>`. The GAV on the maven is correct, but correcting FML will take some time, and was not considered a priority before release. Especially given that this is allowed and within spec of the launcher profile.

So I will leave the ticket open, and we will eventually fix this, just not anytime soon.
