### ISSUE TITLE
Run access transformers after applying patches during setup

### ISSUE THREAD

**Issue by JustRed23** [neoforged/NeoGradle#238]
I am not completely sure if this is the case, but when testing stuff in the neoforge root project, i created a new patch and made an accesstransformer for a variable existing in that patch, making the AT not apply, as the variable was still private

**Comment by lukebemish** [comment]
Well yes, that would make sense. The source patches in neodev are against the AT-ed code -- neo ATs run _before_ patching.

**Comment by JustRed23** [comment]
Ah, i see. Marking as resolved then
