### ISSUE TITLE
No service of type ObjectFactory available when running any gradle task

### ISSUE THREAD

**Issue by lukebemish** [neoforged/NeoGradle#29]
After upgrading to NG 7.0.26, I can no longer run any gradle task whatsoever without an error popping up with a missing service preventing the run; this is in a multiproject context, with neogradle applied only to a subproject. The error occurs when running any gradle task from the terminal.

https://gist.github.com/lukebemish/bb832705e833d8775eb5f73cd83e1a37

**Comment by lukebemish** [comment]
To add more information: I have the `net.neoforged.neogradle.mixin` plugin applied, but it occurs whether or not I use the DSL. Removing the plugin stops the error

**Comment by Matyrobbrt** [comment]
ignore please
