### ISSUE TITLE
Running with `--scan` to publish a build scan causes decompilation and recompilation to happen again

### ISSUE THREAD

**Issue by lukebemish** [neoforged/NeoGradle#56]
As using `--scan` to publish a build scan changes the plugin classpath, using this setting with neogradle causes the caches to miss for the various neoFrom tasks, causing everything to be set up again. This is solidly not great.

**Comment by shartte** [comment]
https://github.com/gradle/gradle/issues/8161#issuecomment-1714174041

**Comment by lukebemish** [comment]
Yep, that's exactly what is happening and it is indeed intended gradle behaviour. It's only an issue here due to neogradle's drastic misuse of up-to-date marking - which is *not* meant to store the sorts of stuff neogradle produces and assume that it won't just miss all the time. Gradle's built-in cache calculation should not be depended on for neogradle artifacts for exactly this reason.

**Comment by marchermans** [comment]
We are depending on Gradles caching right now on purpose, if this is their decision to make external tasks behave like this when --scan is involved then take that up with gradle.

We are working on caching more and more data, but for now this is behaving as intended.
