### ISSUE TITLE
Eclipse runs not working due to missing folder

### ISSUE THREAD

**Issue by CreativeMD** [neoforged/NeoGradle#78]
The eclipse runs do not work if the working directory does not exist. This can be easily fixed by creating the required folders manually. It's a small inconvenience, but would be cool if it could be fixed.

**Comment by Matyrobbrt** [comment]
Did you use the run group?

**Comment by CreativeMD** [comment]
Yes, did so. But the folder does not exist even after running the prepare run task.

**Comment by Speiger** [comment]
o/
@Matyrobbrt Neogradle simply doesn't create the folder upon setup for eclipse users.
And then expect it to be present.

**Comment by Shadows-of-Fire** [comment]
I think the only thing we can do here is have `idePostSync` generate the folders

**Comment by marchermans** [comment]
This is fixed since we now generate the folder when the task is created.
