### ISSUE TITLE
Runtime dynamic dependency can fail to evict existing dependency

### ISSUE THREAD

**Issue by Mumfrey** [neoforged/NeoGradle#97]
Pull Request #52 added support for dynamic runtime dependencies, however it seems that under certain circumstances the original dependency is not evicted in favour of the new dependency:

Per the "direct" usage in #52, I would expect the following to result in the newer dependency ending up in the runtime classpath:
```groovy
dependencies {
    implementation 'org.spongepowered:mixin:0.8.6-SNAPSHOT'
}

runs {
    client {
        dependencies {
            runtime 'org.spongepowered:mixin:0.8.6-SNAPSHOT'
        }
    }
}
```
However the original dependency is still added to the runtime classpath.

**Comment by shartte** [comment]
After some debugging, it relates to https://github.com/gradle/gradle/issues/6881

**Comment by marchermans** [comment]
Fixed in the latest release, we switched to name dependencies fully.
